title: CYAN4S BLOG
email: sih5214p@gmail.com

url: https://cyan4s.github.io/blog
baseurl: /blog

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap