title: CYAN4S BLOG
email: me@cyan4s.com

url: https://blog.cyan4s.com

author:
  twitter: cyan4s

twitter:
  username: cyan4s
  card: summary_large_image

logo: /assets/img/cyan4slogo.png

lang: ko_KR

social:
  name: Inho Son
  links:
    - https://www.cyan4s.com
    - https://github.com/CYAN4S
    - https://twitter.com/cyan4s
    - https://www.behance.net/CYAN4S
    - https://blog.cyan4s.com

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/default/default.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag