title: CYAN4S BLOG
email: sih5214p@gmail.com

url: https://cyan4s.github.io
baseurl: /blog

author:
  twitter: cyan4s

twitter:
  username: cyan4s
  card: summary_large_image

logo: /assets/img/cyan4slogo.png

lang: ko_KR

social:
  name: Inho Son
  links:
    - https://cyan4s.github.io/
    - https://github.com/CYAN4S
    - https://twitter.com/cyan4s
    - https://www.behance.net/CYAN4S
    - https://cyan4s.github.io/blog/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag