title: CYAN4S BLOG
email: me@cyan4s.com
description: >-
  CYAN4S의 기술 블로그입니다.

baseurl: ""
url: https://blog.cyan4s.com

twitter_username: cyan4s
github_username: CYAN4S

author:
  twitter: cyan4s

twitter:
  username: cyan4s
  card: summary_large_image

logo: /assets/img/cyan4slogo.png

lang: ko_KR

social:
  name: Inho Son
  links:
    - https://www.cyan4s.com
    - https://github.com/CYAN4S
    - https://twitter.com/cyan4s
    - https://www.behance.net/CYAN4S
    - https://blog.cyan4s.com

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/default/thumbnail.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

sass:
  style: compressed