title: CYAN4S tech blog
email: sih5214p@gmail.com

url: https://cyan4s.studio
baseurl: /blog

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"