title: CYAN4S TECH BLOG
email: sih5214p@gmail.com

url: https://cyan4s.studio/blog
baseurl: /blog

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "col-2"